name: BetterRent
version: 1.0.0
main: net.betterrent.BetterRent
api-version: 1.21

author: jujudu
description: Plugin de location de maisons avec Vault, WorldEdit et WorldGuard

depend:
  - Vault
  - WorldEdit
  - WorldGuard

commands:

  rent:
    description: Gestion des locations de maisons
    usage: /rent
    aliases:
      - maison
      - house

  rentsetting:
    description: Modifier les paramètres d'une maison
    usage: /rentsetting <maison> <permission> <true/false>
    permission: betterrent.admin


permissions:

  betterrent.admin:
    description: Accès aux commandes administrateur BetterRent
    default: op

  betterrent.rent:
    description: Louer une maison
    default: true
